# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#about"
  weight = 10

[[main]]
  name = "Model"
  url = "/model"
  weight = 20

[[main]]
  name = "Modules"
  url = "/modules"
  weight = 30

[[main]]
  name = "Research"
  url = "/research"
  weight = 40

[[main]]
  name = "News"
  url = "/post"
  weight = 50

#[[main]]
#  name = "The Themes"
#  url = "/themes"
#  identifier = "themes"
#  weight = 20

#[[main]]
#  name = "Food security"
#  url = "/themes/food-security"
#  parent = "themes"
#  weight = 10

#[[main]]
#  name = "Bio based economy"
#  url = "/themes/bio-based-economy"
#  parent = "themes"
#  weight = 20

[[main]]
  name = "Projects"
  url = "/projects"
  weight = 60

[[main]]
  name = "Publications"
  url = "/publication"
  weight = 70

#[[main]]
#  name = "Manual"
#  url = "/manual"
#  weight = 50

[[main]]
  name = "Team"
  url = "/team"
  weight = 80

[[main]]
  name = "Contact"
  url = "/contact"
  weight = 90

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
