---
##########################################################################################
# TEMPLATE FOR PROJECT DESCRIPTIONS 
# Example for IFAD, see https://www.magnet-model.eu/project/ifad/
# # indicates a comment so this part of the content can be safely removed.
##########################################################################################

title: Foodwaste at Member State level 
tags: ["food waste"]
date: "2022-11-29T00:00:00Z"

# Optional external URL for project (note that this will create a direct link and replaces the project detail page).
external_link: ""

# Placement options: 1 = Full column width, 2 = Out-set, 3 = Screen-width
# Focal point options: Smart, Center, TopLeft, Top, TopRight, Left, Right, BottomLeft, Bottom, BottomRight
# No need to add anything here, unless you want to show the featured.png picture only in list of projects but
# not on top of the project description (preview_only: true). You can also add a caption to your featured.png that
# will be placed on top.
image:
  preview_only: false
  placement: ""
  focal_point: ""
  caption: ""

# Add relevant links here. They will be added as icons on top - see examples. If there are no links use ""  
links:
# - icon: chart-line
#   icon_pack: fas
#   name: ""
#   url: ""
url_code: ""
url_pdf: ""
url_slides: ""
url_video: ""

# Slides (optional).
#   Associate this project with Markdown slides.
#   Simply enter your slide deck's filename without extension.
#   E.g. `slides = "example-slides"` references `content/slides/example-slides.md`.
#   Otherwise, set `slides = ""`.
slides: ""

---
By 2050 the world is expected to generate about 3.4 billion tons of waste. A large part of this waste stream could be reused or recycled, however without intervention most of this waste will end up dumped or in landfill or incineration sites. The reuse, recycling and use of waste for materials, chemicals, energy and animal feed can contribute to more sustainable, efficient and integrated bio-based economy. To analyse this within a CGE model, we already extended MAGNET with a circularity module including municipal solid waste generated by households and various options of dealing with waste by including new waste treatment sectors like landfills, waste to energy, recycling and composting sectors. In this project we extended the original household waste model with food waste generation along the supply chain. We model producer food waste in a similar way as household food waste. This means that we a waste margin commodity to intermediate demand of certain food commodities. MAGNET will then be used for an impact assessment of food waste reduction targets.

Contact: [Heleen Bartelings](/author/heleen-bartelings/)
