---
title: BrightSpace proposal has reached the stage of grant agreement preparation
author: Michiel van Dijk
date: '2022-01-11'
slug: brightspace-proposal-has-reached-the-stage-of-grant-agreement-preparation
categories: []

# Add tags below in "" separated with a comma. This will be displayed below and nicely group items with the same tags.
tags: ["planetary boundaries", "climate change"]
subtitle: ''
summary: ''
authors: []
lastmod: '2022-02-11T09:47:01+01:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---

The BrightSpace project, coordinated by Wageningen Economic Research was selected for funding within the Horizon Europe funding schema. The objective of BrightSpace is to design effective and sustainable strategies for assessing and addressing the challenges of EU agriculture to navigate within a safe and just operating space, including planetary boundaries. BrightSpace will provide a set of analytical instruments to experiment, analyse, and coordinate the effects of innovative governance structures and policies related to agriculture to navigate within a safe and just operating space. The project is expected to run from end of 2022 till end of 2027 and features 14 different partners from all over Europe, among others including: Wageningen Economic Research (NLD), Von Thuenen Institute (DEU), International Institure for Applied Systems Analysis (AUT), European Center for Agricultural, Regional and Environmental Policy Research (DEU) and Centro de Investigación y Tecnología Agroalimentaria de Aragón (ESP). 
